services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  backend:
    build: ./server
    container_name: backend
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/redsocialdaw
      - JWT_SECRET=siu
      - PORT=3001
  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true
  mongodb-chat:
    image: mongo
    container_name: mongodb-chat
    ports:
      - "27018:27017"
  microservicio-chat:
    build: ./microservicio-chat
    container_name: microservicio-chat
    ports:
      - "3100:3000"
    volumes:
      - ./microservicio-chat:/app
    stdin_open: true
    tty: true
    depends_on:
      - mongodb-chat
    environment:
      - MONGO_URL=mongodb://mongodb-chat:27017/chat
      - PORT=3000
volumes:
  mongodb_data:
