<definitions targetNamespace="http://localhost:3001/soap" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:app="http://localhost:3001/soap" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

   <message name="GetUser">
      <part name="Email" type="xsd:string" />
   </message>

   <message name="GetUserResponse">
      <part name="UserId" type="xsd:string"/>
      <part name="Nombre" type="xsd:string"/>
      <part name="Apellido" type="xsd:string"/>
      <part name="Email" type="xsd:string"/>
      <part name="ImgRuta" type="xsd:string"/>
      <part name="Ubicacion" type="xsd:string"/>
      <part name="Ocupacion" type="xsd:string"/>
      <part name="VistasPerfil" type="xsd:integer"/>
      <part name="Impresiones" type="xsd:integer"/>
      <part name="CreatedAt" type="xsd:string"/>
      <part name="UpdatedAt" type="xsd:string"/>
   </message>

   <message name="GetPost">
      <part name="PostId" type="xsd:string"/>
   </message>

   <message name="GetPostResponse">
      <part name="PostId" type="xsd:string"/>
      <part name="PostDescripcion" type="xsd:string"/>
      <part name="PostImgRuta" type="xsd:string"/>
      <part name="CreatedAt" type="xsd:string"/>
      <part name="UpdatedAt" type="xsd:string"/>
      <part name="UserId" type="xsd:string"/>
      <part name="UserNombre" type="xsd:string"/>
      <part name="UserApellido" type="xsd:string"/>
      <part name="UserUbicacion" type="xsd:string"/>
   </message>

   <portType name="ZQuery_PortType">
      <operation name="GetUser">
         <input message="GetUser" />
         <output message="GetUserResponse" />
      </operation>
      <operation name="GetPost">
          <input message="GetPost"/>
          <output message="GetPostResponse"/>
      </operation>
   </portType>

   <binding name="ZQuery_Binding" type="ZQuery_PortType">
      <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
      <operation name="GetUser" style="document">
         <soap:operation soapAction="GetUser" />
         <soap:input>
            <soap:body namespace="app" use="literal" />
         </soap:input>

         <soap:output>
            <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal" />
         </soap:output>
      </operation>
      <operation name="GetPost" style="document">
         <soap:operation soapAction="GetPost" />
         <soap:input>
            <soap:body namespace="app" use="literal" />
         </soap:input>

         <soap:output>
            <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal" />
         </soap:output>
      </operation>
   </binding>

   <service name="ZQueryService">
      <documentation>Archivo WSDL para ZQueryService</documentation>
      <port binding="ZQuery_Binding" name="ZQuery_Port">
         <soap:address location="http://localhost:3001/soap" />
      </port>
   </service>
</definitions>